name: cci
channels:
  - conda-forge
dependencies:
  - seaborn
  - matplotlib
  - xarray
  - cartopy
  - dask
  - numpy
  - pyshp
  - python=3.11
  - openpyxl
  - boto3
  - geos
  - pip
  - geopandas
  - pandas
  - paramiko
  - rasterio
  - proj
  - pyproj
  - shapely
  - netcdf4
  - h5py
  - scipy
  - csaps
  - tqdm
prefix:
